# Generated by Django 2.1.3 on 2018-12-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry_pets', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(default='', max_length=100),
        ),
    ]
