# Generated by Django 2.1.3 on 2018-12-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry_pets', '0003_auto_20181207_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Breed',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=100),
        ),
    ]
