# Generated by Django 2.1.3 on 2018-12-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry_pets', '0004_auto_20181207_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adoption',
            field=models.BooleanField(default=False),
        ),
    ]
