# Generated by Django 2.1.3 on 2018-12-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry_pets', '0005_pet_adoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
