# Generated by Django 2.1.3 on 2018-12-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry_pets', '0006_auto_20181208_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
