# Generated by Django 2.1.3 on 2018-12-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry_pets', '0007_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
